### ISSUE TITLE
Gestion des images

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/GPNV#10]
Durant l'analyse, je vais modifier mes mockups. Dès lors j'ai besoin de pouvoir remplacer (ou au moins supprimer) une image existante

**Comment by XSchwab** [comment]
Estimate time: 1h

**Comment by QuentinNev** [comment]
La feature a en réalité déjà été implémentée, mais le fait de drag&drop une image sur un élément ressemblant à **bouton delete** est contre-intuitif. 
Retour à un système de suppression classique 1 bouton par image
