### ISSUE TITLE
Page de profil

### ISSUE THREAD

**Issue by KevinJordil** [CPNV-ES/GPNV#19]
Une fois connecté, lors de l'accès à notre profil les infos ne sont pas chargées correctement

**Comment by XSchwab** [comment]
Estimate time: 3h

**Comment by QuentinNev** [comment]
Uppon Laravel migration from 5.2, someone forgot to add the SubstituteBindings middleware in **app/Http/Kernel.php** so resource couldn't be bound to their model.
